"""Reproduce the structural constants in integrated_chebyshev_buffer_audit.md.

No zero table is required. The script uses the classical closed form
C0 = 2 + EulerGamma - log(4*pi), which under RH equals
sum_rho 1/[rho(1-rho)].
"""

import math

EULER_GAMMA = 0.577215664901532860606512090082402431
C0 = 2.0 + EULER_GAMMA - math.log(4.0 * math.pi)
B0 = 2.0 / 3.0

print(f"critical-line reciprocal mass upper constant C0 = {C0:.15f}")
print(f"prime-square buffer B0 = {B0:.15f}")
print(f"C0/B0 = {C0/B0:.15f}")
print(f"B0/C0 = {B0/C0:.15f}")
print(f"leading margin B0-C0 = {B0-C0:.15f}")

# B_r = Gamma(3/2)/Gamma(r+5/2), generated by recurrence.
B = B0
print("r,B_r,recursive_Sr_upper,ratio_upper")
for r in range(0, 11):
    if r > 0:
        B /= (r + 1.5)  # B_r = B_{r-1}/(r+3/2)
    # From S_r/B_r <= S_0/B_0 < C0/B0.
    S_upper = (C0 / B0) * B
    print(f"{r},{B:.18g},{S_upper:.18g},{S_upper/B:.18g}")
